<a href="https://colab.research.google.com/github/SophieShin/NLP_22_Fall/blob/main/%5BSSH%5Dlab02_pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 2 – Tensors

In [1]:
import torch

## Create empty tensors
- Uninitialised tensors

In [2]:
# 1-D
x = torch.empty(1)
print(x)

# 1-D with two elements
x = torch.empty(2)
print(f"\n1-D tensor\n{x}\n")

# 2-D
x = torch.empty(2,3)
print(f"2-D tensor\n{x}\n")

# 3-D
x = torch.empty(2,3,1)
print("3-D tensor\n",x)


tensor([5.1746e-35])

1-D tensor
tensor([5.1748e-35, 0.0000e+00])

2-D tensor
tensor([[5.1749e-35, 0.0000e+00, 5.0447e-44],
        [0.0000e+00,        nan, 0.0000e+00]])

3-D tensor
 tensor([[[5.1747e-35],
         [0.0000e+00],
         [5.0447e-44]],

        [[0.0000e+00],
         [       nan],
         [0.0000e+00]]])


## Initialise tensors to scalar, random values, zeros or ones

In [3]:
# 0-D tensor (just containing scalar value 3)
x = torch.tensor(3)
# print(x)
print(f'Scalar: {x} has shape {x.shape} and {x.ndim} dimensions\n')

# Random values in the interval [0,1]
x = torch.rand(2,3)
print(f"Random values:\n{x}")
print(x.dtype)

# Zeros
x = torch.zeros(2,3)
print(f"\nZeros:\n{x}")
print(x.dtype)

x = torch.zeros(2,3, dtype=torch.int)
print(f"\nZeros:\n{x}\n")

# Ones
x = torch.ones(2,3)
print(f"Ones:\n{x}")
print(f"Type: {x.dtype}\n")

x = torch.ones(2,3, dtype=torch.double)
print(f"Ones:\n{x}")

Scalar: 3 has shape torch.Size([]) and 0 dimensions

Random values:
tensor([[0.7280, 0.7720, 0.9386],
        [0.8916, 0.5183, 0.1134]])
torch.float32

Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32

Zeros:
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.float32

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


## Construct tensor from data

In [4]:
# Change a list to a tensor
x = torch.tensor([0.5, 2.7])
print(x)

tensor([0.5000, 2.7000])


### Changing tensor data type


In [5]:
x = torch.rand(2,3) * 20
print(x)

# Change to integer
y = x.to(torch.int32)
print(y)

tensor([[10.1694,  0.9949, 11.9459],
        [11.3117, 11.0984, 17.9455]])
tensor([[10,  0, 11],
        [11, 11, 17]], dtype=torch.int32)


### Create a separate copy



In [6]:
a = torch.ones(2, 2)
b = a.clone()

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[1., 1.],
        [1., 1.]])


## Basic tensor operations

- addition, subtraction, multiplication, division

In [7]:
x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

z = torch.add(x,y) # same as z = x + y
print("x + y = ")
print(z)

z = torch.sub(x,y) # same as z = x - y
print("x - y = ")
print(z)

z = torch.mul(x,y) # same as z = x * y
print("x * y = ")
print(z)

z = torch.div(x,y) # same as z = x / y
print("x / y = ")
print(z)


x = 
tensor([[0.9211, 0.6211],
        [0.2535, 0.3436]])

y = 
tensor([[2.1753e-01, 5.5987e-04],
        [8.7876e-01, 3.8097e-02]])

x + y = 
tensor([[1.1386, 0.6216],
        [1.1323, 0.3817]])
x - y = 
tensor([[ 0.7036,  0.6205],
        [-0.6252,  0.3055]])
x * y = 
tensor([[0.2004, 0.0003],
        [0.2228, 0.0131]])
x / y = 
tensor([[4.2344e+00, 1.1093e+03],
        [2.8853e-01, 9.0187e+00]])


### Inplace operations

- any function with a trailing underscore (e.g. ``add_``) will modify the value of the variable in question, in place

In [8]:
x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

# Inplace operations
y.add_(x) # modify y by adding x to it
print(f"y + x = {y}")

y.sub_(x) # modify y by subtracting x from it
print(f"y - x = {y}")

y.mul_(x) # modify y by multiplying x to it
print(f"y * x = {y}")

y.div_(x) # modify y by dividing it by x
print(f"y / x = {y}")


x = 
tensor([[0.4996, 0.9713],
        [0.1346, 0.3451]])

y = 
tensor([[0.7064, 0.0940],
        [0.8101, 0.4007]])

y + x = tensor([[1.2060, 1.0654],
        [0.9447, 0.7457]])
y - x = tensor([[0.7064, 0.0940],
        [0.8101, 0.4007]])
y * x = tensor([[0.3529, 0.0913],
        [0.1090, 0.1383]])
y / x = tensor([[0.7064, 0.0940],
        [0.8101, 0.4007]])


## Accessing tensors

In [9]:
# Slicing
x = torch.rand(5,3)
print(x)

# Get all rows but only first column
print(x[:, 0])

# Get all columns but only the second row
print(x[1, :])

# Get a specific element
print(x[2,2])

# When the tensor returns only ONE element, use item() to get the actual value of that element
print(x[1,1].item())

y = torch.tensor([2.0])
print(y.item())

tensor([[0.1307, 0.4344, 0.8114],
        [0.6497, 0.2021, 0.6468],
        [0.9913, 0.0660, 0.1404],
        [0.3060, 0.1031, 0.0626],
        [0.9976, 0.7721, 0.5298]])
tensor([0.1307, 0.6497, 0.9913, 0.3060, 0.9976])
tensor([0.6497, 0.2021, 0.6468])
tensor(0.1404)
0.20214319229125977
2.0


## Tensor Shape & Dimensions
- The number of dimensions a tensor has is called its rank and the length in each dimension describes its ``shape``.
- To determine the length of each dimension, call ``.shape``
- To determine the number of dimensions it has, call ``.ndim``


In [10]:
x = torch.rand(5,3)
print(f'{x} \nhas shape {x.shape} and {x.ndim} dimensions\n')

tensor([[0.8136, 0.5754, 0.3671],
        [0.1536, 0.5771, 0.8589],
        [0.1695, 0.1480, 0.9114],
        [0.9606, 0.2932, 0.7999],
        [0.0806, 0.4714, 0.6905]]) 
has shape torch.Size([5, 3]) and 2 dimensions



## More on Shapes

- `[1,5,2,6]` has shape (4,) to indicate it has 4 elements and the missing element after the comma means it is a 1-D tensor or array (vector)
- `[[1,5,2,6], [1,2,3,1]]` has shape (2,4) to indicate it has 2 elements (rows) and each of these have 4 elements (columns). This is a 2-D tensor or array (matrix or a list of vectors)
- `[[[1,5,2,6], [1,2,3,1]], [[5,2,1,2], [6,4,3,2]], [[7,8,5,3], [2,2,9,6]]]` has shape (3, 2, 4) to indicate it has 3 elements in the first dimension, and each of these contain 2 elements and each of these contain 4 elements. This is a 3-D tensor or array


## Operations on tensor dimensions
- A tensor dimension is akin to an array's axis. The number of dimensions is called rank.
- A scalar has rank 0, a vector has rank 1, a matrix has rank 2, a cuboid has rank 3, etc.
- Sometimes one wants to do an operation only on a particular dimension, e.g. on the rows only
- Across ``dim=X`` means we do the operation w.r.t to the dimension given and the rest of the dimensions of the tensor stays as they are
- in 2-D tensors, ``dim=0`` refers to the columns while ``dim=1`` refers to the rows


In [11]:
x = torch.tensor([[1,2,3],
                 [4,5,6]])

print(x.shape)
print(f'Summing across dim=0 (columns) gives: {torch.sum(x,dim=0)}')

print(f'Summing across dim=1 (rows) gives: {torch.sum(x,dim=1)}')


torch.Size([2, 3])
Summing across dim=0 (columns) gives: tensor([5, 7, 9])
Summing across dim=1 (rows) gives: tensor([ 6, 15])


## Reshaping tensors
- There are several ways to do this but using ``torch.reshape()`` is the most common
- Also look up ``torch.squeeze(), torch.unsqueeze()`` and ``torch.view()``


In [12]:
x = torch.rand(4,4)
print("Original:")
print(x)
print(x.shape)

# Reshape (flatten) to 1-D
y = x.reshape(16) # number of elements must be the same as original, error otherwise
print("Reshaped to 1-D:")
print(y)

# Reshape to 2-D
y = x.reshape(8,2)
print("Reshaped to 2-D:")
print(y)

# Could leave out one of the dimensions by specifying -1
y = x.reshape(2, -1)
print("Reshaped to 2 x Unspecified 2-D:")
print(y)
print(y.shape)

# Could use unsqueeze(0) to add a dimension at position 0
y = x.unsqueeze(0)
print(f'Using unsqueeze(0) to add dimension from original shape {x.shape} to {y.shape}')

Original:
tensor([[0.6909, 0.9369, 0.1997, 0.0468],
        [0.5561, 0.9963, 0.7813, 0.0164],
        [0.6035, 0.6957, 0.1992, 0.7903],
        [0.6363, 0.3924, 0.3726, 0.8145]])
torch.Size([4, 4])
Reshaped to 1-D:
tensor([0.6909, 0.9369, 0.1997, 0.0468, 0.5561, 0.9963, 0.7813, 0.0164, 0.6035,
        0.6957, 0.1992, 0.7903, 0.6363, 0.3924, 0.3726, 0.8145])
Reshaped to 2-D:
tensor([[0.6909, 0.9369],
        [0.1997, 0.0468],
        [0.5561, 0.9963],
        [0.7813, 0.0164],
        [0.6035, 0.6957],
        [0.1992, 0.7903],
        [0.6363, 0.3924],
        [0.3726, 0.8145]])
Reshaped to 2 x Unspecified 2-D:
tensor([[0.6909, 0.9369, 0.1997, 0.0468, 0.5561, 0.9963, 0.7813, 0.0164],
        [0.6035, 0.6957, 0.1992, 0.7903, 0.6363, 0.3924, 0.3726, 0.8145]])
torch.Size([2, 8])
Using unsqueeze(0) to add dimension from original shape torch.Size([4, 4]) to torch.Size([1, 4, 4])


## Convert between NumPy and PyTorch tensors

- Tensors can work on CPUs and GPUs
- NumPy arrays can only work on CPUs

In [13]:
import torch
import numpy as np

# Tensor to NumPy
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

# b changes when a is modified because they share the same memory space!
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [14]:
import torch
import numpy as np

a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

# Modifying array will modify the tensor as well
a += 2
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## Attach & detach GPU to Pytorch tensors

**Note: Make sure your runtime type is set to GPU when running the below codes**

In [15]:
torch.cuda.is_available()#check if gpu is available

True

In [16]:
device =  torch.device('cuda:0')
tmp_tensors = torch.tensor([0,3,1,2]).to(device)#attach gpu
tmp_tensors

tensor([0, 3, 1, 2], device='cuda:0')

In [17]:
tmp_tensors.cpu().detach().numpy()#detach gpu and make it as a numpy array

array([0, 3, 1, 2])

# Exercise

In [18]:
# 1a. Create a tensor of 100 equally spaced numbers from 0 to 2.
# Assign the tensor to x (Hint: use torch.linspace() )
x = torch.linspace(0,2, 100)
# 1b. Print x
print(x)

tensor([0.0000, 0.0202, 0.0404, 0.0606, 0.0808, 0.1010, 0.1212, 0.1414, 0.1616,
        0.1818, 0.2020, 0.2222, 0.2424, 0.2626, 0.2828, 0.3030, 0.3232, 0.3434,
        0.3636, 0.3838, 0.4040, 0.4242, 0.4444, 0.4646, 0.4848, 0.5051, 0.5253,
        0.5455, 0.5657, 0.5859, 0.6061, 0.6263, 0.6465, 0.6667, 0.6869, 0.7071,
        0.7273, 0.7475, 0.7677, 0.7879, 0.8081, 0.8283, 0.8485, 0.8687, 0.8889,
        0.9091, 0.9293, 0.9495, 0.9697, 0.9899, 1.0101, 1.0303, 1.0505, 1.0707,
        1.0909, 1.1111, 1.1313, 1.1515, 1.1717, 1.1919, 1.2121, 1.2323, 1.2525,
        1.2727, 1.2929, 1.3131, 1.3333, 1.3535, 1.3737, 1.3939, 1.4141, 1.4343,
        1.4545, 1.4747, 1.4949, 1.5152, 1.5354, 1.5556, 1.5758, 1.5960, 1.6162,
        1.6364, 1.6566, 1.6768, 1.6970, 1.7172, 1.7374, 1.7576, 1.7778, 1.7980,
        1.8182, 1.8384, 1.8586, 1.8788, 1.8990, 1.9192, 1.9394, 1.9596, 1.9798,
        2.0000])


In [20]:
# 2. Print the first 5 numbers in x.
print(x[:5])
# 3. Print the last 5 numbers in x
print(x[-5:])

tensor([0.0000, 0.0202, 0.0404, 0.0606, 0.0808])
tensor([1.9192, 1.9394, 1.9596, 1.9798, 2.0000])


In [24]:
# 4a. Create another tensor of 100 random values between 0 and 1.
# Assign the tensor to y (Hint: use torch.rand() )

y = torch.rand(100)
# 4b. Print y
print(y)

tensor([0.0585, 0.8249, 0.7103, 0.3427, 0.9125, 0.8843, 0.0042, 0.6726, 0.0558,
        0.0540, 0.5791, 0.5358, 0.9620, 0.5731, 0.4709, 0.9104, 0.5850, 0.8543,
        0.3024, 0.9983, 0.5880, 0.4517, 0.3051, 0.2683, 0.2903, 0.7761, 0.9671,
        0.9910, 0.0623, 0.1705, 0.8558, 0.3376, 0.1097, 0.6625, 0.9985, 0.9543,
        0.8091, 0.8071, 0.2275, 0.0281, 0.6428, 0.5861, 0.4348, 0.6771, 0.2954,
        0.0017, 0.7998, 0.4445, 0.0591, 0.9927, 0.7697, 0.4858, 0.4215, 0.7564,
        0.2722, 0.8331, 0.4686, 0.6966, 0.1785, 0.5592, 0.2001, 0.7031, 0.2144,
        0.0440, 0.1553, 0.2922, 0.3141, 0.0876, 0.7045, 0.4870, 0.3018, 0.0673,
        0.5599, 0.5280, 0.2779, 0.6000, 0.1995, 0.0158, 0.8717, 0.6757, 0.1117,
        0.5097, 0.6667, 0.4947, 0.1882, 0.5746, 0.2909, 0.6426, 0.5457, 0.0580,
        0.9139, 0.7429, 0.9281, 0.5067, 0.3320, 0.8725, 0.8249, 0.3843, 0.2433,
        0.5035])


In [25]:
# 5a. Multiply x and y, store the result in z
z = x * y

# 5b. Print z
print(z)

tensor([3.5685e-02, 9.0519e-02, 2.9199e-01, 2.8299e-01, 8.6790e-01, 8.2829e-01,
        1.5884e-03, 4.5804e-01, 4.5191e-02, 4.9121e-02, 2.9797e-01, 2.2161e-01,
        8.7018e-01, 5.6825e-01, 2.9700e-01, 4.4217e-01, 2.2719e-01, 6.7184e-02,
        1.2319e-02, 4.4417e-01, 1.2153e-01, 3.5571e-01, 1.2332e-01, 8.3516e-02,
        8.5644e-03, 1.7691e-01, 4.8890e-01, 6.8621e-01, 3.1230e-02, 1.2699e-01,
        3.4118e-01, 9.1470e-02, 2.6755e-02, 2.7571e-01, 3.1775e-01, 5.5011e-01,
        1.2205e-01, 5.3234e-01, 9.8727e-02, 2.5335e-02, 9.7861e-02, 5.3821e-01,
        1.8691e-01, 1.1115e-01, 7.9523e-02, 3.5199e-04, 3.0848e-01, 1.7575e-01,
        1.8946e-02, 4.3574e-01, 4.4439e-01, 2.1161e-01, 4.0241e-01, 2.0235e-01,
        1.5832e-01, 3.4123e-01, 4.6097e-01, 1.9943e-01, 7.0934e-02, 4.0588e-01,
        5.3408e-02, 4.8863e-01, 3.3373e-02, 9.0979e-03, 9.1861e-02, 2.2706e-01,
        1.7067e-01, 2.9319e-02, 5.7015e-01, 4.0134e-01, 2.6043e-01, 2.6275e-02,
        2.0787e-01, 6.7791e-02, 7.0828e-

In [27]:
# 6a. Reshape z to a tensor with 5 rows and 20 columns
# Store reshaped tensor to z2
z2 = z.reshape(5,20)

# 6b. Print z2
print(z2)

tensor([[3.5685e-02, 9.0519e-02, 2.9199e-01, 2.8299e-01, 8.6790e-01, 8.2829e-01,
         1.5884e-03, 4.5804e-01, 4.5191e-02, 4.9121e-02, 2.9797e-01, 2.2161e-01,
         8.7018e-01, 5.6825e-01, 2.9700e-01, 4.4217e-01, 2.2719e-01, 6.7184e-02,
         1.2319e-02, 4.4417e-01],
        [1.2153e-01, 3.5571e-01, 1.2332e-01, 8.3516e-02, 8.5644e-03, 1.7691e-01,
         4.8890e-01, 6.8621e-01, 3.1230e-02, 1.2699e-01, 3.4118e-01, 9.1470e-02,
         2.6755e-02, 2.7571e-01, 3.1775e-01, 5.5011e-01, 1.2205e-01, 5.3234e-01,
         9.8727e-02, 2.5335e-02],
        [9.7861e-02, 5.3821e-01, 1.8691e-01, 1.1115e-01, 7.9523e-02, 3.5199e-04,
         3.0848e-01, 1.7575e-01, 1.8946e-02, 4.3574e-01, 4.4439e-01, 2.1161e-01,
         4.0241e-01, 2.0235e-01, 1.5832e-01, 3.4123e-01, 4.6097e-01, 1.9943e-01,
         7.0934e-02, 4.0588e-01],
        [5.3408e-02, 4.8863e-01, 3.3373e-02, 9.0979e-03, 9.1861e-02, 2.2706e-01,
         1.7067e-01, 2.9319e-02, 5.7015e-01, 4.0134e-01, 2.6043e-01, 2.6275e-02,
       

In [29]:
z2.shape

torch.Size([5, 20])

In [32]:
# 7. Get the sum of each row in z2
print(f'Summing z2 across dim=1 (rows) gives: {torch.sum(z2, dim=1)}')

# 8. Get the mean of each column in z2
print(f'Summing z2 across dim=1 (columns) gives " {torch.sum(z2, dim=0)}')

Summing z2 across dim=1 (rows) gives: tensor([6.3993, 4.5843, 4.8504, 3.9194, 5.5678])
Summing z2 across dim=1 (columns) gives " tensor([0.3971, 1.5032, 0.8897, 0.5690, 1.0854, 1.7701, 1.1326, 1.8531, 0.8056,
        1.0174, 2.0145, 0.8156, 2.2483, 1.4261, 0.9830, 1.8898, 1.4596, 1.0565,
        1.0716, 1.3332])


In [33]:
# 9a. Reshape z to a 3D tensor (keep all the elements)
# Store reshaped tensor to z3
z3 = z.reshape(2, 5, 10)

# 9b. Print z3
print(z3)

tensor([[[3.5685e-02, 9.0519e-02, 2.9199e-01, 2.8299e-01, 8.6790e-01,
          8.2829e-01, 1.5884e-03, 4.5804e-01, 4.5191e-02, 4.9121e-02],
         [2.9797e-01, 2.2161e-01, 8.7018e-01, 5.6825e-01, 2.9700e-01,
          4.4217e-01, 2.2719e-01, 6.7184e-02, 1.2319e-02, 4.4417e-01],
         [1.2153e-01, 3.5571e-01, 1.2332e-01, 8.3516e-02, 8.5644e-03,
          1.7691e-01, 4.8890e-01, 6.8621e-01, 3.1230e-02, 1.2699e-01],
         [3.4118e-01, 9.1470e-02, 2.6755e-02, 2.7571e-01, 3.1775e-01,
          5.5011e-01, 1.2205e-01, 5.3234e-01, 9.8727e-02, 2.5335e-02],
         [9.7861e-02, 5.3821e-01, 1.8691e-01, 1.1115e-01, 7.9523e-02,
          3.5199e-04, 3.0848e-01, 1.7575e-01, 1.8946e-02, 4.3574e-01]],

        [[4.4439e-01, 2.1161e-01, 4.0241e-01, 2.0235e-01, 1.5832e-01,
          3.4123e-01, 4.6097e-01, 1.9943e-01, 7.0934e-02, 4.0588e-01],
         [5.3408e-02, 4.8863e-01, 3.3373e-02, 9.0979e-03, 9.1861e-02,
          2.2706e-01, 1.7067e-01, 2.9319e-02, 5.7015e-01, 4.0134e-01],
         [2

In [35]:
# 10. Solve the following error when running the below code.
first_tensor = torch.tensor([1,2]).to(device)
second_tensor = torch.tensor([0,3]).to(device)
added_mat = first_tensor + second_tensor
print(added_mat)

tensor([1, 5], device='cuda:0')


In [36]:
device

device(type='cuda', index=0)

In [40]:
# 11. Attach the following array to gpu
to_gpu_array = torch.tensor([1,2,3,4]).to(device)